name: build.longterm.kernel

# yamllint disable rule:line-length
# yamllint disable-line rule:truthy
on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.vars.outputs.tag }}
    steps:
      - name: checkout-repository
        uses: actions/checkout@v4

      - name: create-tag
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: check-tag
        env:
          RELEASE_TAG: ${{ steps.vars.outputs.tag }}
        run: |
          echo $RELEASE_TAG
          echo ${{ steps.vars.outputs.tag }}
  build:
    runs-on: ubuntu-latest
    needs: [tag]
    steps:
      - name: checkout-repository
        uses: actions/checkout@v4

      # - uses: actions/checkout@v4
      # - name: "Create Tag"
      #   id: vars
      #   run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      # - name: check-tag
      #   env:
      #     RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
      #   run: |
      #     echo $RELEASE_VERSION
      #     echo ${{ steps.vars.outputs.tag }}

      - name: docker-compose
        id: dokcer-compose
        run: docker-compose up focal

      - name: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-release
          path: workspace/release/*

      - name: release
        if: github.ref == 'refs/heads/longterm'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            workspace/release/kernel_config_*
            workspace/release/*.deb
            workspace/release/build_params*
            workspace/release/sha256sum*
          tag_name: v${{ needs.tag.outputs.tag }}
          draft: false
          body: >
            Installation instructions are given
            [here](https://github.com/bluerapik/t2-ubuntu-kernel#installation).
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
