name: build.longterm.kernel

# yamllint disable rule:line-length
# yamllint disable-line rule:truthy
on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{  github.ref_name }}
    steps:
      - name: tag
        run: |
          echo "GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "github.ref_name: ${{  github.ref_name }}"

  build:
    runs-on: ubuntu-latest
    needs: [tag]
    steps:
      - name: checkout-repository
        uses: actions/checkout@v4

      - name: docker-compose
        id: dokcer-compose
        run: docker-compose up focal

      - name: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-release
          path: workspace/release/*

      - name: release
        if: github.ref == 'refs/heads/longterm'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            workspace/release/kernel_config_*
            workspace/release/*.deb
            workspace/release/build_params*
            workspace/release/sha256sum*
          tag_name: v${{ needs.tag.outputs.tag }}
          draft: false
          body: >
            Installation instructions are given
            [here](https://github.com/bluerapik/t2-ubuntu-kernel#installation).
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
